name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # você pode adicionar inputs opcionais aqui (cores, size etc.)

      - name: Debug - listar dist
        run: |
          echo "Workspace root:"
          ls -la
          echo "Conteúdo de dist (se existir):"
          ls -la dist || true

      - name: Commit snake to 'output' branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: ":snake: update snake"
          add: "dist/snake.svg"
          branch: output
